#  Introduction to Object Oriented Programming in Python
one of the popular approach to solve a programming probleb by creating an objects
This is known as Object Oriented Programming.     
An object has two characterstics:    
1.attributes(name,age,colour)   
2.behaviour(learn,study,singing,dance) 

# In Python, the concept OOP follow these things:   

1.Inheritance  
2.Encapsulation  
3.Ploymorphism  

class:-A class is the blue print of the object<br>
object:- Blue print of the class or instance of the class or physical activity<br>
methods:-part of a class and can be called with a object<br>
construcyors:-part of a class and can be called automatically when the object of the class is created

def test():
    print("test() for function")
test()

In [ ]:
class className:
    #some functions and variables
    #function--used to perform the specific activity
    #variables--Data(memory)

In [8]:
class Demo:
    def test(self):
        print("test() for the class and method")
        return
obj= Demo()#example for obj creation
obj.test()# call for method

test() for the class and method


In [2]:
class Demo1:
    def fact(self,n):
        #return the factorial
        fact=1;
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p1=Demo1()
print(p1.fact(5))#120

120


In [19]:
# Method
# def test(self,para1,para2)
class Demo2:
        def accept(self,p1,p2):
            self.p1=p1
            self.p2=p2
        def display(self):
            print("p1= ",p2)
            print("p2= ",p2)
            
         
c1= Demo2()
c1.accept(10,20)
c1.display()

NameError: name 'p2' is not defined

In [20]:
class Demo2:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=Demo2(10,20)
print(c1.add(100,200))

300


In [4]:
import numpy as np
lst=[1,0,2,5,3,6,9,5]
array=np.array(lst)
print(array.shape)
print(array.dtype)

(8,)
int32


In [6]:
#Append some data---horizontally
#hstack(array1,array2)------willbe automatically arranged horizontally

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.hstack([a1,a2]))

[1 2 3 4 5 6]


In [7]:
#Append some data---vertically
#vstack(array1,array2)------willbe automatically arranged vertically

a1=np.array([1,2,3])
a2=np.array([4,5,6])
print(np.vstack([a1,a2]))

[[1 2 3]
 [4 5 6]]


In [9]:
#To Generate random numbers
a1=np.random.normal(5,0.5,10)
print(a1)

[5.48503222 4.77274017 5.10462954 5.22808783 5.09020842 5.00006509
 4.63592898 4.78643527 5.38349317 5.45150603]


In [12]:
# numpy.zeros() and numpy.one()
# generate an array with all zeros-----np.zeros()
#numpy.zeros(shape,dtype=float,order='c')
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [14]:
np.zeros((2,2),dtype=np.int32)

array([[0, 0],
       [0, 0]])

In [18]:
#np.ones(shape,dtype=float,order='c')
np.ones((4,3),dtype=np.int32)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [23]:
A=np.matrix(np.ones((4,4),dtype=np.int64))
np.asarray(A)[2][1]=5
print(A)

[[1 1 1 1]
 [1 1 1 1]
 [1 5 1 1]
 [1 1 1 1]]


In [26]:
A=np.matrix(np.ones((4,4),dtype=np.int32))
np.asarray(A)[1][3]=14
np.asarray(A)[3][3]=16
print(A)

[[ 1  1  1  1]
 [ 1  1  1 14]
 [ 1  1  1  1]
 [ 1  1  1 16]]


In [29]:
# arrange()...particular
# Numpy .arrange(start,end,step)
# start - value
# end - value
# step - gap between one value and another

import numpy as np
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [31]:
np.arange(2,20,2)
np.arange(1,25,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [32]:
# indexing and slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print("first row :",a1[0])

first row : [1 2 3]


In [33]:
# indexing and slicing of numpy
a1 = np.array([(1,2,3),(4,5,6)])
print("second row :",a1[1])

second row : [4 5 6]


In [34]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing column :",a1[:,1])

slicing column : [2 5]


In [37]:
a1 = np.array([(1,2,3),(4,5,6)])
print("slicing  last column :",a1[:,2])

slicing  last column : [3 6]


In [38]:
a1 = np.array([(1,2,3),(4,5,6)])
print("row and column :",a1[1,:2])

row and column : [4 5]


In [40]:
#some math operatiopns on given random number
# Min
#Max
#Mean
#Median
a1=np.random.normal(5,1,10)
print(a1)
print(np.min(a1))
print(np.max(a1))
print(np.mean(a1))
print(np.median(a1))

[4.0846344  5.38972436 6.01327718 4.04449746 5.02817733 4.18548085
 4.18565703 5.26660805 6.43818588 3.50585135]
3.5058513451649826
6.438185875492868
4.81420938845148
4.606917179817124


In [41]:
\
#Multiply of 1D arrays
#numpy.dot(x,y)--
c1=np.array([1,2])
c2=np.array([4,5])
np.dot(c1,c2)

c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

b1=np.array([([1,5]),([6,9])])
b2=np.array([([1,3]),([1,6])])
np.matmul(b1,b2)

array([[ 6, 33],
       [15, 72]])


# Pandas Basics
 Python is one of the popular programming language for data analysis<br>    
Python is offering the Lib called Pandas used for importing and analysing pretty much faster and easier also        
Pandas DataFrames        
    
    Data Analysis with Python

In [2]:

import pandas as pd
dict={"Name":["Anil","Akhil","Dinesh","Harsha","Ajay","Kranth"],"EmailID":["anil@gmail.com","akhil@gmail.com","dinesh@gmail.com","harsha@gmail.com","ajay@gmail.com","kranth@gmail.com"],"MobileNumber":[999,888,777,888,777,999],"Address":["Hyd","Hyd","Hyd","Hyd","Hyd","Hyd"],}
b=pd.DataFrame(dict)
print(b)

     Name           EmailID  MobileNumber Address
0    Anil    anil@gmail.com           999     Hyd
1   Akhil   akhil@gmail.com           888     Hyd
2  Dinesh  dinesh@gmail.com           777     Hyd
3  Harsha  harsha@gmail.com           888     Hyd
4    Ajay    ajay@gmail.com           777     Hyd
5  Kranth  kranth@gmail.com           999     Hyd


In [3]:
b.index=["01","02","03","04","05","06"]
print(b)

      Name           EmailID  MobileNumber Address
01    Anil    anil@gmail.com           999     Hyd
02   Akhil   akhil@gmail.com           888     Hyd
03  Dinesh  dinesh@gmail.com           777     Hyd
04  Harsha  harsha@gmail.com           888     Hyd
05    Ajay    ajay@gmail.com           777     Hyd
06  Kranth  kranth@gmail.com           999     Hyd


In [4]:

#Supermarket.csv-Analysis(which product have high % of sp and which have least)

import pandas as pd
products=pd.read_csv('Filename.csv')
print(products)

FileNotFoundError: [Errno 2] File b'Filename.csv' does not exist: b'Filename.csv'

In [5]:
import pandas as pd
product_sellingData=pd.read_csv('FileName.csv',index_col=1)
print(product_sellingData)

FileNotFoundError: [Errno 2] File b'FileName.csv' does not exist: b'FileName.csv'